name: Unit Tests

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: cachix/install-nix-action@v29

      - name: Build And Test
        uses: actions/checkout@v4
        with:
          repository: hytech-racing/drivebrain_software
          ref: ${{ github.ref }}

      - name: Enter the development environment
        run: | 
          nix develop .#tests
          nix flake metadata 

        
      