name: Unit Tests

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: cachix/install-nix-action@v29

      - name: Open Development Environment
        uses: actions/checkout@v4
        with:
          repository: hytech-racing/drivebrain_software
          ref: ${{ github.ref }}
      
      - run: nix develop .#tests

      - name: Create Build Directory and Generate Makefile
        run: >- 
          mkdir build
          -cd build
          -cmake ..
        
      