name: Unit Tests

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: cachix/install-nix-action@v29

      - name: Build And Test
        uses: actions/checkout@v4
        with:
          repository: hytech-racing/HT_proto
          ref: ref/heads/master

      - name: Enter the development environment
        run: nix develop .#tests

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..

      

        
      